function [eegData,featureOutput,labelOutput]=extract_single_file(patientID,segID,targetCh,Fs,L,W,S,H,lf,uf)
% EXTRACT_SINGLE_FILE  Plot EEG data of a single file and plot fft of specified channel.
%                      (If seizure, plot EEG data around seizure onset and FFT for entire seizure time;
%                      If non-seizure, plot EEG for speicified time range and FFT for entire data segment.)
% Usage:    [eegData,featureOutput,labelOutput]=extract_single_file(patientID,segID,Fs,L,W,S,H,lf,uf)
%           [eegData,featureOutput,labelOutput]=extract_single_file(patientID,segID)
% Inputs:   patientID       -char array of patient ID
%           segID           -char array of segment (file) ID
%           targetCh        -channel picked in FFT plotting (default:FP2F4)
%           Fs(opt)         -sample rate (default:256)
%           L(opt)          -interval length (default:2)
%           W(opt)          -number of intervals (default:3)
%           S(opt)          -seconds into seizure of data taken (default:20)
%           H(opt)          -hours of non-seizure data needed (default:1)
%           lf(opt)         -lower bound of frequency range (default:0)
%           uf(opt)         -upper bound of frequency range (default:24)
% Outputs:  eegData         -EEG Data
%           featureOutput   -features generated by selected data
%           labelOutput     -labels corresponding to selected data
% Note:     EEG plotting parameters need to be changed within function.
%           used function: get_seg_feature(), time2sec()

%% default value for optinal arguments
if nargin < 10
    uf = 24;
end
if nargin < 9
    lf = 0;
end
if nargin < 8
  H = 1;    % default hours of non-seizure data % currently not used
end
if nargin < 7
  S = 20;   % default seconds into seizure
end
if nargin < 6
  W = 3;    % default number of intervals
end
if nargin < 5
  L = 2;    % default interval length 
end
if nargin < 4
  Fs = 256; % default sample rate
end
if nargin < 3
  targetCh = 'FP2F4'; % target channel picked for plotting FFT
end


%% load data
filePath = ['../Data/chb',patientID,'mat'];
labels = [];
segIDs = {};
startTs = {};
endTs = {};
seizureInfos = {};
% summary
summaryFile = [filePath,'/','SNchb',patientID,'summary'];
summary = load(summaryFile);
[nseg,~] = size(summary.info);

for i = 1:nseg
    segIDs = [segIDs,summary.info{i,2}];
    startTs = [startTs,summary.info{i,3}];
    endTs = [endTs,summary.info{i,4}];
    labels = [labels,summary.info{i,5}];
    seizureInfos = [seizureInfos,summary.info{i,6}];
end
baseTime = time2sec(startTs{1}); % starting time

% index of specified segment
idx = find(strcmp(segIDs,segID));
%% load data from file
fileName = ['SNchb',patientID,'_',segID,'.mat'];
file = load([filePath,'/',fileName]);
fName = fieldnames(file);
channels = (file.(fName{1}){1})';
eegData = file.(fName{1}){2};

%% PARAMETERS
% EEG
% relative starting and ending time
ta = 1/Fs;
tb = size(eegData,2)/Fs-1;
% ta = 80;
% tb = 100;
plot_count = 0;

%% plot EEG data (of specified time range)
data = eegData(:,ta*Fs:tb*Fs);
plot_count = plot_count+1;
plotEEG(plot_count,data,channels);
title(['EEG Data of ',patientID,'\_',segID]);

%% plot FFT of EEG of target channel
chIdx = find(strcmp(channels,targetCh));
chData = data(chIdx,:);
plot_count = plot_count+1;
% plotFFT(plot_count,chData,lf,uf,Fs);
plotFFT(plot_count,chData);
title(['FFT of EEG of channel ',targetCh,' (from time ',num2str(ta),' to ',num2str(tb),')']);

%% seizure or non-seizure
 if labels(idx)==0 % non-seizure    
    disp('Non-Seizure');
    baseT = time2sec(startTs{idx});
    startT = 0;
    endT = time2sec(endTs{idx})-baseT;
    if endT<startT % one day more
        endT = endT+time2sec('24:00:00');
    end
%     timeMin = startT;
    timeMax = endT; 
    T_tilt = W*L; % time idx for first X_T_tilt
    [segFeatureOutput,segLabelOutput]=get_seg_feature(eegData,T_tilt,timeMax,0,L,W,Fs);
    
 else % seizure   
     disp('Seizure')
     sInfo = seizureInfos{idx};
     seizureI = fieldnames(sInfo);
     for j = 1:length(seizureI)
        seizurePeriod = sInfo.(seizureI{j});
        seizureStart = seizurePeriod{1}
        seizureEnd = seizurePeriod{2}
        
        % plot EEG data around seizure onset
        ta = seizureStart-10;
        tb = seizureEnd+10;
        data = eegData(:,ta*Fs:tb*Fs);       
        plot_count = plot_count+1;
        plotEEG(plot_count,data,channels,ta);
        hold on 
        line([seizureStart seizureStart],get(gca,'YLim'),'Color','r');
        line([seizureEnd seizureEnd],get(gca,'YLim'),'Color','r');
        title(['EEG Data of ',patientID,'\_',segID,' (Seizure Onset: ',num2str(seizureStart),', Offset: ',num2str(seizureEnd),')']);
        
        % plot FFT of target channel EEG data
        baseT = seizureStart-(W-1)*L;
        timeMin = baseT;
        timeMax = min(seizureEnd,seizureStart+S);   
        seizure_data = eegData(:,seizureStart*Fs:(seizureStart+2)*Fs);  
        chSeizure_data = seizure_data(chIdx,:);       
        plot_count = plot_count+1;
        plotFFT(plot_count,chSeizure_data,lf,uf,Fs);
        title(['Seizure Onset Data FFT: 2s into seizure onset at',num2str(seizureStart),'s']);
       
        % energy band
        T_tilt = seizureStart+L; % time idx for first X_T_tilt
        [segFeatureOutput,segLabelOutput]=get_seg_feature(eegData,T_tilt,timeMax,1,L,W,Fs);      
     end    
 end
 
featureOutput = [segFeatureOutput];
labelOutput = [segLabelOutput];

end